package publictestnet

import("context";"crypto/sha256";"encoding/hex";"errors";"fmt";"time";"github.com/chrisbirster/battlebunnywealth/internal/testnet")
var(ErrInvalidCandidate=errors.New("invalid validator candidate application");ErrCandidateNotEligible=errors.New("validator candidate is not eligible");ErrCandidateClockSkew=errors.New("validator candidate timestamp outside allowed skew"))
type CandidateApplication struct{NetworkID string `json:"networkId"`;Validator testnet.Validator `json:"validator"`;Provider string `json:"provider"`;EvidenceID string `json:"evidenceId"`;SubmittedUnix int64 `json:"submittedUnix"`;Signature string `json:"signature"`}
type Eligibility struct{Attested bool;Authority int64;Provider string;JoinedAt time.Time}
type EligibilityVerifier interface{VerifyCandidate(context.Context,CandidateApplication)(Eligibility,error)}
type AdmissionService struct{NetworkID string;Registry *testnet.ActivationRegistry;Verifier EligibilityVerifier;ClockSkew time.Duration}
func BuildCandidateApplication(networkID string,v testnet.Validator,provider,evidenceID string,privateKey any,now time.Time)(CandidateApplication,error){v.Genesis=false;v.Active=false;v.Authority=0;if v.ID==""{v.ID=candidateID(v.PublicKey)};a:=CandidateApplication{NetworkID:networkID,Validator:v,Provider:provider,EvidenceID:evidenceID,SubmittedUnix:now.UTC().Unix()};sig,err:=testnet.Sign(v.Algorithm,privateKey,candidateMessage(a));if err!=nil{return CandidateApplication{},err};a.Signature=sig;return a,nil}
func(s *AdmissionService)Submit(ctx context.Context,a CandidateApplication,now time.Time)error{if s==nil||s.Registry==nil||s.Verifier==nil||a.NetworkID!=s.NetworkID||a.Provider==""||a.EvidenceID==""{return ErrInvalidCandidate};skew:=s.ClockSkew;if skew<=0{skew=5*time.Minute};submitted:=time.Unix(a.SubmittedUnix,0);if submitted.Before(now.Add(-skew))||submitted.After(now.Add(skew)){return ErrCandidateClockSkew};v:=a.Validator;if v.ID!=candidateID(v.PublicKey)||v.PublicKey==""||v.Algorithm==""||v.AccountID==""||v.DeviceID==""{return ErrInvalidCandidate};if !testnet.VerifySignature(v.Algorithm,v.PublicKey,candidateMessage(a),a.Signature){return ErrInvalidCandidate};e,err:=s.Verifier.VerifyCandidate(ctx,a);if err!=nil{return err};if !e.Attested||e.Authority<=0||e.Provider!=a.Provider{return ErrCandidateNotEligible};joined:=e.JoinedAt;if joined.IsZero(){joined=now.UTC()};v.Genesis=false;v.Active=false;v.Authority=e.Authority;s.Registry.AddCandidate(testnet.ValidatorCandidate{Validator:v,Provider:e.Provider,Attested:true,JoinedAt:joined.UTC()});return nil}
func(s *AdmissionService)Pending()int{if s==nil||s.Registry==nil{return 0};return s.Registry.Pending()}
func(s *AdmissionService)Active()[]testnet.Validator{if s==nil||s.Registry==nil{return nil};return s.Registry.Active()}
func candidateID(publicKey string)string{sum:=sha256.Sum256([]byte(publicKey));return hex.EncodeToString(sum[:16])}
func candidateMessage(a CandidateApplication)string{v:=a.Validator;return fmt.Sprintf("bbw-validator-application/v1\nnetwork=%s\nvalidator=%s\naccount=%s\ndevice=%s\nalgorithm=%s\npublicKey=%s\nprovider=%s\nevidence=%s\nsubmitted=%d",a.NetworkID,v.ID,v.AccountID,v.DeviceID,v.Algorithm,v.PublicKey,a.Provider,a.EvidenceID,a.SubmittedUnix)}
