package publictestnet

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"sync"

	"github.com/chrisbirster/battlebunnywealth/internal/carrot"
	"github.com/chrisbirster/battlebunnywealth/internal/testnet"
)

const (ConsensusStateVersion=1;FeePoolAccount="system:pending-fees")
type StateAccount struct{Account string `json:"account"`;BalanceAtoms int64 `json:"balanceAtoms"`;Nonce uint64 `json:"nonce"`}
type ConsensusSnapshot struct{Version int `json:"version"`;NetworkID string `json:"networkId"`;CarrotPolicyHash string `json:"carrotPolicyHash"`;Height uint64 `json:"height"`;SettledRewardHeight uint64 `json:"settledRewardHeight"`;Accounts []StateAccount `json:"accounts"`}
type ConsensusState struct{mu sync.RWMutex;genesis testnet.Genesis;networkID string;policy carrot.Policy;balances map[string]int64;nonces map[string]uint64;rewardAddressByID map[string]string;height uint64;settledRewardHeight uint64}

func NewConsensusState(genesis testnet.Genesis,policy carrot.Policy)(*ConsensusState,error){if err:=genesis.Validate();err!=nil{return nil,err};if err:=policy.Validate();err!=nil{return nil,err};if genesis.CarrotPolicyHash!=policy.Hash(){return nil,errors.New("CARROT policy hash mismatch")};s:=&ConsensusState{genesis:genesis,networkID:genesis.NetworkID,policy:policy,balances:map[string]int64{},nonces:map[string]uint64{},rewardAddressByID:map[string]string{}};for _,a:=range policy.Allocations{s.balances[a.Account]=a.Atoms};for _,v:=range genesis.Validators{s.rewardAddressByID[v.ID]=rewardAddress(v)};if err:=s.validateConservationLocked();err!=nil{return nil,err};return s,nil}
func rewardAddress(v testnet.Validator)string{if ValidAddress(v.RewardAddress){return v.RewardAddress};return "validator:"+v.ID}
func(s *ConsensusState)Root()string{s.mu.RLock();defer s.mu.RUnlock();return s.rootLocked()}
func(s *ConsensusState)Preview(t testnet.Transition)(string,error){s.mu.RLock();c:=s.cloneLocked();s.mu.RUnlock();if err:=c.apply(t);err!=nil{return "",err};return c.rootLocked(),nil}
func(s *ConsensusState)Commit(t testnet.Transition)(string,error){s.mu.Lock();defer s.mu.Unlock();c:=s.cloneLocked();if err:=c.apply(t);err!=nil{return "",err};s.balances=c.balances;s.nonces=c.nonces;s.height=c.height;s.settledRewardHeight=c.settledRewardHeight;return s.rootLocked(),nil}
func(s *ConsensusState)Balance(a string)int64{s.mu.RLock();defer s.mu.RUnlock();return s.balances[a]}
func(s *ConsensusState)Nonce(a string)uint64{s.mu.RLock();defer s.mu.RUnlock();return s.nonces[a]}
func(s *ConsensusState)Height()uint64{s.mu.RLock();defer s.mu.RUnlock();return s.height}
func(s *ConsensusState)SettledRewardHeight()uint64{s.mu.RLock();defer s.mu.RUnlock();return s.settledRewardHeight}
func(s *ConsensusState)Snapshot()ConsensusSnapshot{s.mu.RLock();defer s.mu.RUnlock();return s.snapshotLocked()}
func(s *ConsensusState)ValidateConservation()error{s.mu.RLock();defer s.mu.RUnlock();return s.validateConservationLocked()}
func(s *ConsensusState)SupplyReport()carrot.SupplyReport{s.mu.RLock();defer s.mu.RUnlock();fu:=carrot.FounderUnlockedAt(s.height);fl:=carrot.FounderAllocationAtoms-fu;pr:=s.balances[carrot.AccountParticipation];released:=carrot.ParticipationReserveAtoms-pr;tr:=s.balances[carrot.AccountEcosystem]+s.balances[carrot.AccountCommunity]+s.balances[carrot.AccountSecurity];circ:=carrot.MaxSupplyAtoms-fl-pr-tr;if circ<0{circ=0};return carrot.SupplyReport{Height:s.height,MaxSupplyAtoms:carrot.MaxSupplyAtoms,MaxSupplyCARROT:carrot.FormatAtoms(carrot.MaxSupplyAtoms),FounderUnlockedAtoms:fu,FounderLockedAtoms:fl,ParticipationReleasedAtoms:released,ParticipationRemainingAtoms:pr,TreasuryReservedAtoms:tr,CirculatingAtoms:circ,CirculatingCARROT:carrot.FormatAtoms(circ)}}
func(s *ConsensusState)cloneLocked()*ConsensusState{c:=&ConsensusState{genesis:s.genesis,networkID:s.networkID,policy:s.policy,balances:map[string]int64{},nonces:map[string]uint64{},rewardAddressByID:map[string]string{},height:s.height,settledRewardHeight:s.settledRewardHeight};for k,v:=range s.balances{c.balances[k]=v};for k,v:=range s.nonces{c.nonces[k]=v};for k,v:=range s.rewardAddressByID{c.rewardAddressByID[k]=v};return c}
func(s *ConsensusState)apply(t testnet.Transition)error{if t.NetworkID!=s.networkID{return testnet.ErrWrongNetwork};if t.Height!=s.height+1{return testnet.ErrInvalidHeight};var settlement *FinalitySettlement;seenTx:=map[string]struct{}{};for _,op:=range t.Operations{if op.Type==SettlementOperationType{x,err:=ParseSettlementOperation(op);if err!=nil{return err};if settlement!=nil{return errors.New("duplicate finality settlement")};settlement=&x}}
	if t.Height==1{if settlement!=nil{return errors.New("height 1 cannot settle prior finality")}}else{if settlement==nil{return errors.New("missing prior finality settlement")};if t.PreviousFinalized==nil{return errors.New("previous finalized block required")};if err:=s.settlePrevious(t.Height-1,*t.PreviousFinalized,*settlement);err!=nil{return err}}
	for _,op:=range t.Operations{switch op.Type{case"noop",SettlementOperationType:continue;case TransactionOperationType:tx,err:=ParseTransactionOperation(op);if err!=nil{return err};if _,ok:=seenTx[tx.ID];ok{return ErrDuplicateTransaction};seenTx[tx.ID]=struct{}{};if err:=s.applyTransaction(tx,t.Height);err!=nil{return err};default:return fmt.Errorf("unsupported consensus operation %q",op.Type)}};s.height=t.Height;return s.validateConservationLocked()}
func(s *ConsensusState)settlePrevious(rewardHeight uint64,previous testnet.FinalizedBlock,settlement FinalitySettlement)error{if s.settledRewardHeight+1!=rewardHeight{return fmt.Errorf("reward settlement gap: have %d want %d",s.settledRewardHeight,rewardHeight)};if previous.Block.Height!=rewardHeight||settlement.RewardHeight!=rewardHeight||settlement.BlockHash!=previous.Block.Hash||settlement.Round!=previous.Block.Round{return errors.New("settlement does not match previous block")};committee:=testnet.SelectCommittee(s.genesis.Validators,s.genesis.Config.CommitteeTarget,previous.Block.PreviousHash,previous.Block.Height,previous.Block.Round);quorum:=testnet.QuorumFor(s.genesis.Config,len(committee));seen:=map[string]struct{}{};ids:=[]string{};for _,vote:=range settlement.Votes{if vote.NetworkID!=s.networkID||vote.Height!=previous.Block.Height||vote.Round!=previous.Block.Round||vote.BlockHash!=previous.Block.Hash{continue};if _,dup:=seen[vote.ValidatorID];dup{continue};var validator testnet.Validator;found:=false;for _,v:=range committee{if v.ID==vote.ValidatorID{validator=v;found=true;break}};if !found||!testnet.VerifyCommitVote(vote,validator){continue};seen[vote.ValidatorID]=struct{}{};ids=append(ids,vote.ValidatorID)};if len(ids)<quorum{return testnet.ErrInsufficientQuorum};sort.Strings(ids);reward:=carrot.RewardAtHeight(rewardHeight);if reward>s.balances[carrot.AccountParticipation]{return errors.New("participation reserve exhausted")};s.balances[carrot.AccountParticipation]-=reward;s.distributeToValidators(reward,ids);fees:=s.balances[FeePoolAccount];if fees>0{s.balances[FeePoolAccount]=0;s.distributeToValidators(fees,ids)};s.settledRewardHeight=rewardHeight;return nil}
func(s *ConsensusState)distributeToValidators(amount int64,ids []string){if amount<=0||len(ids)==0{return};base:=amount/int64(len(ids));rem:=int(amount%int64(len(ids)));for i,id:=range ids{share:=base;if i<rem{share++};addr:=s.rewardAddressByID[id];if addr==""{addr="validator:"+id};s.balances[addr]+=share}}
func(s *ConsensusState)applyTransaction(tx SignedTransaction,height uint64)error{expected:=s.nonces[tx.From];if err:=ValidateTransaction(tx,s.networkID,height,expected);err!=nil{return err};total:=tx.AmountAtoms+tx.FeeAtoms;if total<tx.AmountAtoms||s.balances[tx.From]<total{return carrot.ErrInsufficientBalance};s.balances[tx.From]-=total;s.balances[tx.To]+=tx.AmountAtoms;if tx.FeeAtoms>0{s.balances[FeePoolAccount]+=tx.FeeAtoms};s.nonces[tx.From]=expected+1;return nil}
func(s *ConsensusState)snapshotLocked()ConsensusSnapshot{keys:=map[string]struct{}{};for k:=range s.balances{keys[k]=struct{}{}};for k:=range s.nonces{keys[k]=struct{}{}};names:=make([]string,0,len(keys));for k:=range keys{names=append(names,k)};sort.Strings(names);a:=make([]StateAccount,0,len(names));for _,k:=range names{a=append(a,StateAccount{Account:k,BalanceAtoms:s.balances[k],Nonce:s.nonces[k]})};return ConsensusSnapshot{Version:ConsensusStateVersion,NetworkID:s.networkID,CarrotPolicyHash:s.policy.Hash(),Height:s.height,SettledRewardHeight:s.settledRewardHeight,Accounts:a}}
func(s *ConsensusState)rootLocked()string{raw,_:=json.Marshal(s.snapshotLocked());sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func(s *ConsensusState)validateConservationLocked()error{var total int64;for account,b:=range s.balances{if b<0{return fmt.Errorf("negative balance %s",account)};total+=b};if total!=carrot.MaxSupplyAtoms{return fmt.Errorf("TEST-CARROT supply conservation failed: got %d want %d",total,carrot.MaxSupplyAtoms)};return nil}
