package publictestnet

import (
	"fmt"
	"testing"
	"time"

	"github.com/chrisbirster/battlebunnywealth/internal/carrot"
	"github.com/chrisbirster/battlebunnywealth/internal/testnet"
)

type executionFixture struct{genesis testnet.Genesis;validators []testnet.Validator;keys map[string]any;wallets map[string]Wallet;engines []*testnet.Engine;states []*ConsensusState;now time.Time}
func newExecutionFixture(t *testing.T,nodes int)*executionFixture{t.Helper();now:=time.Unix(1_800_000_000,0).UTC();validators:=make([]testnet.Validator,4);keys:=map[string]any{};wallets:=map[string]Wallet{};for i:=0;i<4;i++{pub,priv,err:=testnet.GenerateValidatorKey(testnet.AlgorithmEd25519);if err!=nil{t.Fatal(err)};w,err:=GenerateWallet();if err!=nil{t.Fatal(err)};id:=fmt.Sprintf("validator-%02d",i+1);validators[i]=testnet.Validator{ID:id,AccountID:fmt.Sprintf("account-%d",i+1),DeviceID:fmt.Sprintf("phone-%d",i+1),Algorithm:testnet.AlgorithmEd25519,PublicKey:pub,RewardAddress:w.Address(),Authority:1000};keys[id]=priv;wallets[id]=w};genesis,err:=testnet.NewGenesis("bbw-public-state-test",now,testnet.DefaultProtocolConfig(),validators);if err!=nil{t.Fatal(err)};f:=&executionFixture{genesis:genesis,validators:genesis.Validators,keys:keys,wallets:wallets,now:now};for i:=0;i<nodes;i++{s,err:=NewConsensusState(genesis,carrot.DefaultPolicy());if err!=nil{t.Fatal(err)};e,err:=testnet.NewEngineWithStateMachine(genesis,s);if err!=nil{t.Fatal(err)};f.states=append(f.states,s);f.engines=append(f.engines,e)};return f}
func(f *executionFixture)finalize(t *testing.T,ops []testnet.Operation)(testnet.FinalizedBlock,[]testnet.Validator){t.Helper();height:=f.engines[0].Height()+1;head:=f.engines[0].Status().FinalizedHash;committee:=testnet.SelectCommittee(f.validators,f.genesis.Config.CommitteeTarget,head,height,0);proposer,ok:=testnet.ExpectedProposer(committee,height,0);if !ok{t.Fatal("no proposer")};block,err:=f.engines[0].Draft(0,proposer.ID,ops,f.now.Add(time.Duration(height)*time.Minute));if err!=nil{t.Fatal(err)};proposal,err:=testnet.BuildProposal(block,proposer,f.keys[proposer.ID]);if err!=nil{t.Fatal(err)};for _,e:=range f.engines{if err:=e.HandleProposal(proposal);err!=nil{t.Fatal(err)}};quorum:=testnet.QuorumFor(f.genesis.Config,len(committee));signers:=committee[:quorum];for _,v:=range signers{vote,err:=testnet.BuildVote(block,v,f.keys[v.ID]);if err!=nil{t.Fatal(err)};for _,e:=range f.engines{if _,err:=e.HandleVote(vote);err!=nil{t.Fatal(err)}}};blocks:=f.engines[0].Finalized();return blocks[len(blocks)-1],signers}
func settlement(t *testing.T,b testnet.FinalizedBlock)testnet.Operation{t.Helper();op,err:=SettlementOperation(b);if err!=nil{t.Fatal(err)};return op}

func TestConsensusTransactionsConvergeAndRestore(t *testing.T){f:=newExecutionFixture(t,3);b1,signers1:=f.finalize(t,nil);b2,_:=f.finalize(t,[]testnet.Operation{settlement(t,b1)});payer:=f.wallets[signers1[0].ID];recipient,_:=GenerateWallet();if f.states[0].Balance(payer.Address())<=0{t.Fatal("finality reward was not settled")};tx,err:=NewSignedTransaction(f.genesis.NetworkID,recipient.Address(),1000,7,0,100,payer);if err!=nil{t.Fatal(err)};txop,_:=TransactionOperation(tx);b3,_:=f.finalize(t,[]testnet.Operation{settlement(t,b2),txop});if f.states[0].Balance(recipient.Address())!=1000||f.states[0].Nonce(payer.Address())!=1{t.Fatal("transaction state not applied")};root:=f.engines[0].Status().StateRoot;for i,e:=range f.engines[1:]{if e.Status().StateRoot!=root{t.Fatalf("engine %d state root diverged",i+2)};if f.states[i+1].Balance(recipient.Address())!=1000{t.Fatal("replicated balance diverged")}};if f.states[0].Balance(FeePoolAccount)!=7{t.Fatal("fee not held for next-block settlement")};f.finalize(t,[]testnet.Operation{settlement(t,b3)});if f.states[0].Balance(FeePoolAccount)!=0{t.Fatal("fee pool not settled")};if err:=f.states[0].ValidateConservation();err!=nil{t.Fatal(err)}
	dir:=t.TempDir();store,err:=testnet.OpenStore(dir,f.genesis);if err!=nil{t.Fatal(err)};for _,b:=range f.engines[0].Finalized(){if err:=store.Append(b);err!=nil{t.Fatal(err)}};restoredState,err:=NewConsensusState(f.genesis,carrot.DefaultPolicy());if err!=nil{t.Fatal(err)};restored,err:=testnet.NewEngineWithStateMachine(f.genesis,restoredState);if err!=nil{t.Fatal(err)};if err:=store.Restore(restored);err!=nil{t.Fatal(err)};if restored.Status().StateRoot!=f.engines[0].Status().StateRoot||restoredState.Balance(recipient.Address())!=1000||restoredState.Nonce(payer.Address())!=1{t.Fatal("restart replay did not reconstruct consensus state")}}

func TestInvalidAndReplayTransactionsCannotBeProposed(t *testing.T){f:=newExecutionFixture(t,1);b1,signers1:=f.finalize(t,nil);b2,_:=f.finalize(t,[]testnet.Operation{settlement(t,b1)});unfunded,_:=GenerateWallet();to,_:=GenerateWallet();bad,_:=NewSignedTransaction(f.genesis.NetworkID,to.Address(),1,0,0,100,unfunded);badop,_:=TransactionOperation(bad);if _,err:=f.engines[0].Draft(0,f.expectedProposer(t).ID,[]testnet.Operation{settlement(t,b2),badop},f.now);err==nil{t.Fatal("insufficient-balance transaction was draftable")};payer:=f.wallets[signers1[0].ID];good,_:=NewSignedTransaction(f.genesis.NetworkID,to.Address(),1,0,0,100,payer);goodop,_:=TransactionOperation(good);b3,_:=f.finalize(t,[]testnet.Operation{settlement(t,b2),goodop});if _,err:=f.engines[0].Draft(0,f.expectedProposer(t).ID,[]testnet.Operation{settlement(t,b3),goodop},f.now);err==nil{t.Fatal("replayed nonce was draftable")}}
func(f *executionFixture)expectedProposer(t *testing.T)testnet.Validator{t.Helper();height:=f.engines[0].Height()+1;c:=testnet.SelectCommittee(f.validators,f.genesis.Config.CommitteeTarget,f.engines[0].Status().FinalizedHash,height,0);p,ok:=testnet.ExpectedProposer(c,height,0);if !ok{t.Fatal("no proposer")};return p}

func TestHeightTwoRequiresCanonicalSettlementOperation(t *testing.T){f:=newExecutionFixture(t,1);b1,_:=f.finalize(t,nil);p:=f.expectedProposer(t);if _,err:=f.engines[0].Draft(0,p.ID,nil,f.now);err==nil{t.Fatal("height two without settlement was accepted")};committee:=testnet.SelectCommittee(f.validators,f.genesis.Config.CommitteeTarget,b1.Block.PreviousHash,b1.Block.Height,b1.Block.Round);quorum:=testnet.QuorumFor(f.genesis.Config,len(committee));alt:=b1;alt.Certificate.Votes=nil;for i:=len(committee)-1;i>=0&&len(alt.Certificate.Votes)<quorum;i--{v:=committee[i];vote,err:=testnet.BuildVote(b1.Block,v,f.keys[v.ID]);if err!=nil{t.Fatal(err)};alt.Certificate.Votes=append(alt.Certificate.Votes,vote)};op:=settlement(t,alt);if _,err:=f.engines[0].Draft(0,p.ID,[]testnet.Operation{op},f.now);err!=nil{t.Fatalf("valid alternate quorum certificate was not canonicalizable: %v",err)}}
