package publictestnet

import(
"crypto/ed25519";"crypto/sha256";"encoding/base64";"encoding/hex";"errors";"fmt";"net";"net/url";"sort";"sync";"time";
"github.com/chrisbirster/battlebunnywealth/internal/testnet")
var(ErrInvalidAnnouncement=errors.New("invalid public-node announcement");ErrPeerDirectoryFull=errors.New("public peer directory full");ErrPeerHostLimit=errors.New("public peer host limit reached");ErrPeerPrefixLimit=errors.New("public peer network-prefix limit reached"))
type NodeAnnouncement struct{NetworkID string `json:"networkId"`;NodeID string `json:"nodeId"`;PublicKey string `json:"publicKey"`;URL string `json:"url"`;TimestampUnix int64 `json:"timestampUnix"`;ExpiresUnix int64 `json:"expiresUnix"`;Nonce string `json:"nonce"`;Signature string `json:"signature"`}
func BuildAnnouncement(networkID,endpoint,nonce string,key testnet.NodeKey,now time.Time,ttl time.Duration)(NodeAnnouncement,error){if ttl<=0||ttl>24*time.Hour{return NodeAnnouncement{},ErrInvalidAnnouncement};a:=NodeAnnouncement{NetworkID:networkID,NodeID:key.ID(),PublicKey:key.PublicText(),URL:endpoint,TimestampUnix:now.UTC().Unix(),ExpiresUnix:now.Add(ttl).UTC().Unix(),Nonce:nonce};if err:=validateEndpoint(endpoint);err!=nil{return NodeAnnouncement{},err};a.Signature=base64.RawURLEncoding.EncodeToString(ed25519.Sign(key.Private,[]byte(announcementMessage(a))));return a,nil}
func VerifyAnnouncement(a NodeAnnouncement,networkID string,now time.Time)error{if a.NetworkID!=networkID||a.NodeID==""||a.Nonce==""||a.ExpiresUnix<=a.TimestampUnix{return ErrInvalidAnnouncement};if err:=validateEndpoint(a.URL);err!=nil{return err};if now.Unix()<a.TimestampUnix-300||now.Unix()>a.TimestampUnix+300||a.ExpiresUnix<=now.Unix()||a.ExpiresUnix>now.Add(24*time.Hour).Unix(){return ErrInvalidAnnouncement};pub,err:=base64.RawURLEncoding.DecodeString(a.PublicKey);if err!=nil||len(pub)!=ed25519.PublicKeySize||nodeID(ed25519.PublicKey(pub))!=a.NodeID{return ErrInvalidAnnouncement};sig,err:=base64.RawURLEncoding.DecodeString(a.Signature);if err!=nil||!ed25519.Verify(ed25519.PublicKey(pub),[]byte(announcementMessage(a)),sig){return ErrInvalidAnnouncement};return nil}
func announcementMessage(a NodeAnnouncement)string{return fmt.Sprintf("bbw-public-node/v1\nnetwork=%s\nnode=%s\npublicKey=%s\nurl=%s\ntimestamp=%d\nexpires=%d\nnonce=%s",a.NetworkID,a.NodeID,a.PublicKey,a.URL,a.TimestampUnix,a.ExpiresUnix,a.Nonce)}
func nodeID(pub ed25519.PublicKey)string{sum:=sha256.Sum256(pub);return hex.EncodeToString(sum[:16])}
func validateEndpoint(raw string)error{u,err:=url.Parse(raw);if err!=nil||(u.Scheme!="http"&&u.Scheme!="https")||u.Host==""||u.User!=nil||u.Fragment!=""{return ErrInvalidAnnouncement};return nil}
type Directory struct{mu sync.Mutex;network string;max int;perHost int;perPrefix int;peers map[string]NodeAnnouncement}
func NewDirectory(networkID string,maxPeers,maxPerHost int)*Directory{if maxPeers<=0{maxPeers=128};if maxPerHost<=0{maxPerHost=4};perPrefix:=16;if perPrefix>maxPeers{perPrefix=maxPeers};return &Directory{network:networkID,max:maxPeers,perHost:maxPerHost,perPrefix:perPrefix,peers:map[string]NodeAnnouncement{}}}
func(d *Directory)Upsert(a NodeAnnouncement,now time.Time)error{if err:=VerifyAnnouncement(a,d.network,now);err!=nil{return err};d.mu.Lock();defer d.mu.Unlock();d.pruneLocked(now);if _,ok:=d.peers[a.NodeID];ok{d.peers[a.NodeID]=a;return nil};if len(d.peers)>=d.max{return ErrPeerDirectoryFull};u,_:=url.Parse(a.URL);host:=u.Hostname();prefix:=peerPrefix(host);hostCount,prefixCount:=0,0;for _,p:=range d.peers{pu,_:=url.Parse(p.URL);ph:=pu.Hostname();if ph==host{hostCount++};if prefix!=""&&peerPrefix(ph)==prefix{prefixCount++}};if hostCount>=d.perHost{return ErrPeerHostLimit};if prefix!=""&&prefixCount>=d.perPrefix{return ErrPeerPrefixLimit};d.peers[a.NodeID]=a;return nil}
func peerPrefix(host string)string{ip:=net.ParseIP(host);if ip==nil{return ""};if v4:=ip.To4();v4!=nil{return fmt.Sprintf("v4:%d.%d.%d",v4[0],v4[1],v4[2])};v6:=ip.To16();if v6==nil{return ""};return fmt.Sprintf("v6:%x%x%x%x%x%x",v6[0],v6[1],v6[2],v6[3],v6[4],v6[5])}
func(d *Directory)List(now time.Time)[]NodeAnnouncement{d.mu.Lock();defer d.mu.Unlock();d.pruneLocked(now);out:=make([]NodeAnnouncement,0,len(d.peers));for _,p:=range d.peers{out=append(out,p)};sort.Slice(out,func(i,j int)bool{return out[i].NodeID<out[j].NodeID});return out}
func(d *Directory)pruneLocked(now time.Time){for id,p:=range d.peers{if p.ExpiresUnix<=now.Unix(){delete(d.peers,id)}}}
