package publictestnet

import(
"encoding/json";"net/http";"net/http/httptest";"strings";"testing";"time";
"github.com/chrisbirster/battlebunnywealth/internal/carrot";"github.com/chrisbirster/battlebunnywealth/internal/testnet")
func TestTransactionOperationRoundTrip(t *testing.T){a,_:=GenerateWallet();b,_:=GenerateWallet();tx,_:=NewSignedTransaction("public",b.Address(),10,0,0,20,a);op,err:=TransactionOperation(tx);if err!=nil{t.Fatal(err)};got,err:=ParseTransactionOperation(op);if err!=nil{t.Fatal(err)};if got.ID!=tx.ID||got.Signature!=tx.Signature{t.Fatal("transaction operation changed")}}
func TestGovernanceRequiresDistinctValidVotes(t *testing.T){validators:=make([]testnet.Validator,4);keys:=make([]any,4);for i:=range validators{pub,priv,_:=testnet.GenerateValidatorKey(testnet.AlgorithmEd25519);validators[i]=testnet.Validator{ID:candidateID(pub),Algorithm:testnet.AlgorithmEd25519,PublicKey:pub};keys[i]=priv};p:=NewGovernanceProposal("public",GovernanceUpgrade,carrot.DefaultPolicy().Hash(),10,100,3);votes:=make([]GovernanceVote,3);for i:=0;i<3;i++{votes[i],_ = BuildGovernanceVote(p,validators[i],keys[i],true)};result,err:=TallyGovernance(p,validators,votes,50);if err!=nil{t.Fatal(err)};if !result.Approved||result.Approvals!=3{t.Fatalf("result=%+v",result)};dup:=append(votes,votes[0]);if _,err:=TallyGovernance(p,validators,dup,50);err==nil{t.Fatal("duplicate governance vote accepted")}}
func TestTreasuryGovernanceIsDryRun(t *testing.T){p:=NewGovernanceProposal("public",GovernanceTreasuryDryRun,carrot.DefaultPolicy().Hash(),1,20,3);if err:=p.Validate();err!=nil{t.Fatal(err)};if p.ExecutionEnabled{t.Fatal("treasury execution enabled")}}
func TestPublicHTTPAdmitsSignedTransaction(t *testing.T){now:=time.Now().UTC();ledger,_:=NewPublicLedger(carrot.DefaultPolicy());a,_:=GenerateWallet();b,_:=GenerateWallet();_,_=ledger.FundAtHeight(1,[]string{a.Address()});pool:=NewMempool("public",8);server:=&HTTPServer{NetworkID:"public",Directory:NewDirectory("public",8,2),Mempool:pool,Ledger:ledger,Height:func()uint64{return 1}};tx,_:=NewSignedTransaction("public",b.Address(),10,0,0,20,a);raw,_:=json.Marshal(tx);req:=httptest.NewRequest(http.MethodPost,"/v1/public/transactions",strings.NewReader(string(raw)));req.Header.Set("Content-Type","application/json");rec:=httptest.NewRecorder();server.ServeHTTP(rec,req);if rec.Code!=http.StatusAccepted{t.Fatalf("status=%d body=%s",rec.Code,rec.Body.String())};if pool.Count()!=1{t.Fatal("transaction not admitted")};_ = now}
