package publictestnet

import("crypto/sha256";"encoding/hex";"encoding/json";"errors";"fmt";"sort";"github.com/chrisbirster/battlebunnywealth/internal/testnet")
var(ErrInvalidGovernanceProposal=errors.New("invalid public-testnet governance proposal");ErrInvalidGovernanceVote=errors.New("invalid public-testnet governance vote"))
const(GovernanceUpgrade="protocol-upgrade";GovernanceTreasuryDryRun="treasury-dry-run")
type GovernanceProposal struct{NetworkID string `json:"networkId"`;Kind string `json:"kind"`;PayloadHash string `json:"payloadHash"`;CreatedHeight uint64 `json:"createdHeight"`;VotingEndsHeight uint64 `json:"votingEndsHeight"`;RequiredVotes int `json:"requiredVotes"`;ExecutionEnabled bool `json:"executionEnabled"`;ID string `json:"id"`}
type GovernanceVote struct{ProposalID string `json:"proposalId"`;ValidatorID string `json:"validatorId"`;Approve bool `json:"approve"`;Signature string `json:"signature"`}
type GovernanceResult struct{ProposalID string `json:"proposalId"`;ValidVotes int `json:"validVotes"`;Approvals int `json:"approvals"`;Rejections int `json:"rejections"`;Approved bool `json:"approved"`;ExecutionEnabled bool `json:"executionEnabled"`}
func NewGovernanceProposal(networkID,kind,payloadHash string,created,ends uint64,required int)GovernanceProposal{execution:=kind==GovernanceUpgrade;p:=GovernanceProposal{NetworkID:networkID,Kind:kind,PayloadHash:payloadHash,CreatedHeight:created,VotingEndsHeight:ends,RequiredVotes:required,ExecutionEnabled:execution};if kind==GovernanceTreasuryDryRun{p.ExecutionEnabled=false};p.ID=governanceProposalID(p);return p}
func(p GovernanceProposal)Validate()error{if p.NetworkID==""||(p.Kind!=GovernanceUpgrade&&p.Kind!=GovernanceTreasuryDryRun)||len(p.PayloadHash)!=64||p.VotingEndsHeight<=p.CreatedHeight||p.RequiredVotes<=0||p.ID!=governanceProposalID(p){return ErrInvalidGovernanceProposal};if p.Kind==GovernanceTreasuryDryRun&&p.ExecutionEnabled{return ErrInvalidGovernanceProposal};return nil}
func BuildGovernanceVote(p GovernanceProposal,v testnet.Validator,privateKey any,approve bool)(GovernanceVote,error){if err:=p.Validate();err!=nil{return GovernanceVote{},err};vote:=GovernanceVote{ProposalID:p.ID,ValidatorID:v.ID,Approve:approve};sig,err:=testnet.Sign(v.Algorithm,privateKey,governanceVoteMessage(vote));if err!=nil{return GovernanceVote{},err};vote.Signature=sig;return vote,nil}
func TallyGovernance(p GovernanceProposal,validators []testnet.Validator,votes []GovernanceVote,currentHeight uint64)(GovernanceResult,error){if err:=p.Validate();err!=nil{return GovernanceResult{},err};if currentHeight>p.VotingEndsHeight{return GovernanceResult{},ErrInvalidGovernanceProposal};byID:=map[string]testnet.Validator{};for _,v:=range validators{byID[v.ID]=v};seen:=map[string]struct{}{};result:=GovernanceResult{ProposalID:p.ID,ExecutionEnabled:p.ExecutionEnabled};sort.Slice(votes,func(i,j int)bool{return votes[i].ValidatorID<votes[j].ValidatorID});for _,vote:=range votes{if vote.ProposalID!=p.ID{return GovernanceResult{},ErrInvalidGovernanceVote};if _,dup:=seen[vote.ValidatorID];dup{return GovernanceResult{},ErrInvalidGovernanceVote};v,ok:=byID[vote.ValidatorID];if !ok||!testnet.VerifySignature(v.Algorithm,v.PublicKey,governanceVoteMessage(vote),vote.Signature){return GovernanceResult{},ErrInvalidGovernanceVote};seen[vote.ValidatorID]=struct{}{};result.ValidVotes++;if vote.Approve{result.Approvals++}else{result.Rejections++}};result.Approved=result.Approvals>=p.RequiredVotes;return result,nil}
func governanceProposalID(p GovernanceProposal)string{p.ID="";raw,_:=json.Marshal(p);sum:=sha256.Sum256(raw);return hex.EncodeToString(sum[:])}
func governanceVoteMessage(v GovernanceVote)string{return fmt.Sprintf("bbw-public-governance-v1\nproposal=%s\nvalidator=%s\napprove=%t",v.ProposalID,v.ValidatorID,v.Approve)}
