package publictestnet

import("context";"fmt";"time";"github.com/chrisbirster/battlebunnywealth/internal/carrot";"github.com/chrisbirster/battlebunnywealth/internal/testnet")
type SmokeReport struct{FakeNodesAttempted int `json:"fakeNodesAttempted"`;PeersAccepted int `json:"peersAccepted"`;PeersRejected int `json:"peersRejected"`;InvalidTransactions int `json:"invalidTransactionsRejected"`;ValidTransactions int `json:"validTransactionsAccepted"`;PhoneFarmCandidates int `json:"phoneFarmCandidates"`;ActivatedAfterMaturity int `json:"activatedAfterMaturity"`}
type smokeVerifier struct{now time.Time}
func(s smokeVerifier)VerifyCandidate(_ context.Context,a CandidateApplication)(Eligibility,error){return Eligibility{Attested:true,Authority:1000,Provider:a.Provider,JoinedAt:s.now},nil}
func RunSmoke(attackers int)(SmokeReport,error){if attackers<=0{attackers=100};now:=time.Unix(1_800_000_000,0).UTC();r:=SmokeReport{FakeNodesAttempted:attackers,PhoneFarmCandidates:attackers};d:=NewDirectory("bbw-pop-public-testnet-v1",64,4);for i:=0;i<attackers;i++{k,err:=testnet.GenerateNodeKey();if err!=nil{return r,err};a,err:=BuildAnnouncement("bbw-pop-public-testnet-v1",fmt.Sprintf("http://203.0.113.10:%d",10000+i),fmt.Sprintf("n-%d",i),k,now,time.Hour);if err!=nil{return r,err};if d.Upsert(a,now)==nil{r.PeersAccepted++}else{r.PeersRejected++}}
	ledger,err:=NewPublicLedger(carrot.DefaultPolicy());if err!=nil{return r,err};wa,_:=GenerateWallet();wb,_:=GenerateWallet();if _,err:=ledger.FundAtHeight(1,[]string{wa.Address()});err!=nil{return r,err};pool:=NewMempool("bbw-pop-public-testnet-v1",256);tx,err:=NewSignedTransaction("bbw-pop-public-testnet-v1",wb.Address(),1000,0,0,10,wa);if err!=nil{return r,err};if err:=pool.Admit(tx,1,ledger.Nonce(wa.Address()));err!=nil{return r,err};r.ValidTransactions=1;for i:=0;i<attackers;i++{bad:=tx;bad.Signature=fmt.Sprintf("bad-%d",i);bad.ID=fmt.Sprintf("bad-%d",i);if pool.Admit(bad,1,ledger.Nonce(wa.Address()))!=nil{r.InvalidTransactions++}}
	genesis:=make([]testnet.Validator,4);for i:=range genesis{genesis[i]=testnet.Validator{ID:fmt.Sprintf("genesis-%d",i),PublicKey:fmt.Sprintf("g-%d",i),Active:true,Genesis:true,Authority:1000}};registry:=testnet.NewActivationRegistry(testnet.DefaultActivationPolicy(),genesis);admission:=&AdmissionService{NetworkID:"bbw-pop-public-testnet-v1",Registry:registry,Verifier:smokeVerifier{now:now}};for i:=0;i<attackers;i++{pub,priv,err:=testnet.GenerateValidatorKey(testnet.AlgorithmEd25519);if err!=nil{return r,err};v:=testnet.Validator{ID:candidateID(pub),AccountID:fmt.Sprintf("farm-account-%d",i),DeviceID:fmt.Sprintf("farm-device-%d",i),Algorithm:testnet.AlgorithmEd25519,PublicKey:pub};app,err:=BuildCandidateApplication(admission.NetworkID,v,"google-play-integrity",fmt.Sprintf("evidence-%d",i),priv,now);if err!=nil{return r,err};if err:=admission.Submit(context.Background(),app,now);err!=nil{return r,err}};r.ActivatedAfterMaturity=len(registry.ActivateEligible(now.Add(30*24*time.Hour)));return r,nil}
