package game

import (
	"path/filepath"
	"testing"
	"time"
)

func TestOfflineEarningsAreAutomaticAndCapped(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); service, err := NewService(func() time.Time { return now }, NewMemoryStore()); if err != nil { t.Fatal(err) }; initial, _ := service.Snapshot(); if initial.IncomePerSecond != 39 { t.Fatalf("income=%d", initial.IncomePerSecond) }; now = now.Add(12 * time.Hour); after, err := service.Snapshot(); if err != nil { t.Fatal(err) }; want := int64(39 * 8 * 60 * 60); if after.AccruedBunnyBucks != want { t.Fatalf("accrued=%d want %d", after.AccruedBunnyBucks, want) }; if after.Telemetry.OfflineAccruals != 1 { t.Fatalf("offline accruals=%d", after.Telemetry.OfflineAccruals) } }
func TestUpgradeAndSynergy(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); service, _ := NewService(func() time.Time { return now }, NewMemoryStore()); now = now.Add(8 * time.Hour); service.Snapshot(); for i := 0; i < 4; i++ { if _, err := service.UpgradeBusiness("carrot-logistics"); err != nil { t.Fatal(err) } }; for i := 0; i < 4; i++ { if _, err := service.UpgradeBusiness("scrap-salvage"); err != nil { t.Fatal(err) } }; snapshot, _ := service.Snapshot(); var logistics BusinessView; for _, b := range snapshot.Businesses { if b.ID == "carrot-logistics" { logistics = b } }; if logistics.IncomePerSecond != 55 { t.Fatalf("income=%d", logistics.IncomePerSecond) }; if snapshot.Telemetry.UpgradesPurchased != 8 { t.Fatalf("upgrades=%d", snapshot.Telemetry.UpgradesPurchased) } }
func TestSeasonLifecycleTurnInArchiveAndUnlock(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); service, _ := NewService(func() time.Time { return now }, NewMemoryStore()); now = now.Add(30 * time.Minute); service.Snapshot(); turnedPhase, err := service.AdvanceSeasonForDevelopment(); if err != nil { t.Fatal(err) }; if turnedPhase.Season.Phase != SeasonTurnIn { t.Fatalf("phase=%s", turnedPhase.Season.Phase) }; if _, err := service.TurnInSeason(); err != nil { t.Fatal(err) }; archived, err := service.AdvanceSeasonForDevelopment(); if err != nil { t.Fatal(err) }; if len(archived.SeasonHistory) != 1 { t.Fatalf("history=%d", len(archived.SeasonHistory)) }; if archived.Story.Location != "Scrap Row" { t.Fatalf("location=%s", archived.Story.Location) }; if archived.Season.Phase != SeasonActive { t.Fatalf("next phase=%s", archived.Season.Phase) }; if archived.RankedPowerAffected { t.Fatal("season progression must not affect ranked power") } }
func TestStoryAndWarrenPersist(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); path := filepath.Join(t.TempDir(), "state.json"); store := NewFileStore(path); service, _ := NewService(func() time.Time { return now }, store); if _, err := service.AdvanceStory(); err != nil { t.Fatal(err) }; if _, err := service.UpdateWarren("scrap-yard"); err != nil { t.Fatal(err) }; reloaded, err := NewService(func() time.Time { return now }, store); if err != nil { t.Fatal(err) }; snapshot, _ := reloaded.Snapshot(); if snapshot.Story.CurrentBeat != 1 || snapshot.Warren.Theme != "scrap-yard" { t.Fatalf("story=%+v warren=%+v", snapshot.Story, snapshot.Warren) } }
func TestProfileValidationAndPersistence(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); path := filepath.Join(t.TempDir(), "game-state.json"); store := NewFileStore(path); service, _ := NewService(func() time.Time { return now }, store); profile := PlayerProfile{Name: "Boomtail", Callsign: "Fuse", Fur: "charcoal", Ears: "battle-worn", Uniform: "night-black"}; if _, err := service.UpdateProfile(profile); err != nil { t.Fatal(err) }; reloaded, err := NewService(func() time.Time { return now }, store); if err != nil { t.Fatal(err) }; snapshot, _ := reloaded.Snapshot(); if snapshot.Player.Name != "Boomtail" || !contains(snapshot.Player.Cosmetics, "Recruit Patch") { t.Fatalf("player=%+v", snapshot.Player) } }
func TestOnboardingProgressPersists(t *testing.T) { now := time.Date(2026, 9, 11, 12, 0, 0, 0, time.UTC); service, _ := NewService(func() time.Time { return now }, NewMemoryStore()); for i := 0; i < 8; i++ { service.AdvanceOnboarding() }; snapshot, _ := service.Snapshot(); if snapshot.OnboardingStep != 6 { t.Fatalf("onboarding=%d", snapshot.OnboardingStep) } }
