import * as stylex from "@stylexjs/stylex";
import { For, Show, createSignal } from "solid-js";
import Shell from "../components/Shell";
import { authApi, type Account } from "../lib/authApi";
import { createBrowserDeviceKey } from "../lib/deviceKey";

export default function AccountRoute() {
  const [account,setAccount]=createSignal<Account>(); const [displayName,setDisplayName]=createSignal(""); const [did,setDID]=createSignal(""); const [deviceName,setDeviceName]=createSignal("This browser"); const [message,setMessage]=createSignal("Checking service record…"); const [busy,setBusy]=createSignal("");
  const load=async()=>{try{const me=await authApi.me();setAccount(me);setDID(me.atproto?.did??"");setMessage("Account secured by passkey.")}catch{setAccount(undefined);setMessage("Create an account or sign in with a passkey.")}}; void load();
  const run=async(label:string,fn:()=>Promise<Account>,success:string)=>{setBusy(label);try{const next=await fn();setAccount(next);setDID(next.atproto?.did??"");setMessage(success)}catch(error){setMessage(error instanceof Error?error.message:"Request failed.")}finally{setBusy("")}};
  const register=()=>run("register",()=>authApi.register(displayName()),"Passkey account created. Your Battle Bunny state is now owned by this account.");
  const login=()=>run("login",()=>authApi.login(),"Signed in with passkey.");
  const addDevice=()=>run("device",async()=>authApi.enrollDevice(deviceName(),"web",await createBrowserDeviceKey()),"Browser device enrolled. Browser enrollment remains unattested; native iOS/Android apps perform platform attestation.");
  const logout=async()=>{setBusy("logout");try{await authApi.logout();setAccount(undefined);setMessage("Signed out.")}finally{setBusy("")}};
  return <Shell><section {...stylex.props(styles.wrap)}><div {...stylex.props(styles.eyebrow)}>ACCOUNT + IDENTITY / v0.7</div><h1 {...stylex.props(styles.title)}>Your bunny. Your keys.</h1><p {...stylex.props(styles.lede)}>Passkeys own the account. ATProto is an optional portable profile link. Device keys and platform attestation are separate security signals because neither an account nor a phone is proof of one unique human.</p><div {...stylex.props(styles.notice)}>{message()}</div>
    <Show when={account()} fallback={<section {...stylex.props(styles.card)}><h2>Create or recover your account</h2><p {...stylex.props(styles.muted)}>A passkey uses your phone, password manager, or security key. No password is stored by Battle Bunny Wealth.</p><label {...stylex.props(styles.field)}><span>Display name</span><input value={displayName()} maxlength="40" onInput={e=>setDisplayName(e.currentTarget.value)} placeholder="Boomtail" /></label><div {...stylex.props(styles.actions)}><button type="button" disabled={busy()!==""||displayName().trim().length<2} onClick={()=>void register()} {...stylex.props(styles.primary)}>Create with passkey</button><button type="button" disabled={busy()!==""} onClick={()=>void login()} {...stylex.props(styles.secondary)}>Sign in with passkey</button></div></section>}>
      <div {...stylex.props(styles.grid)}><section {...stylex.props(styles.card)}><div {...stylex.props(styles.eyebrow)}>ACCOUNT</div><h2>{account()!.displayName}</h2><dl {...stylex.props(styles.details)}><div><dt>Passkeys</dt><dd>{account()!.passkeyCount}</dd></div><div><dt>Account ID</dt><dd>{account()!.id.slice(0,12)}…</dd></div></dl><div {...stylex.props(styles.actions)}><button type="button" disabled={busy()!==""} onClick={()=>void run("passkey",()=>authApi.addPasskey(),"Additional passkey added.")} {...stylex.props(styles.secondary)}>Add passkey</button><button type="button" disabled={busy()!==""} onClick={()=>void logout()} {...stylex.props(styles.danger)}>Sign out</button></div></section>
      <section {...stylex.props(styles.card)}><div {...stylex.props(styles.eyebrow)}>ATPROTO PROFILE LINK</div><h2>Portable identity</h2><p {...stylex.props(styles.muted)}>The DID link is still profile metadata, not proof of personhood or device integrity. It grants no network authority by itself.</p><label {...stylex.props(styles.field)}><span>DID</span><input value={did()} onInput={e=>setDID(e.currentTarget.value)} placeholder="did:plc:..." /></label><div {...stylex.props(styles.actions)}><button type="button" disabled={busy()!==""||!did().startsWith("did:plc:")} onClick={()=>void run("did",()=>authApi.linkATProto(did()),"ATProto profile resolved and linked as unverified.")} {...stylex.props(styles.primary)}>Resolve + link</button><Show when={account()!.atproto}><button type="button" disabled={busy()!==""} onClick={()=>void run("did",()=>authApi.unlinkATProto(),"ATProto link removed.")} {...stylex.props(styles.secondary)}>Remove</button></Show></div><Show when={account()!.atproto}><div {...stylex.props(styles.binding)}><strong>{account()!.atproto!.handle||account()!.atproto!.did}</strong><span>{account()!.atproto!.status}</span></div></Show></section></div>
      <section {...stylex.props(styles.card,styles.devices)}><div {...stylex.props(styles.eyebrow)}>DEVICES</div><h2>Enrollment + attestation</h2><p {...stylex.props(styles.muted)}>Web devices use locally stored P-256 keys and stay unattested. Native iOS uses App Attest plus a Secure Enclave mission key; Android uses Play Integrity plus Android Keystore/StrongBox where available. Extra active devices receive diminishing Proof-of-Play contribution.</p><div {...stylex.props(styles.actions)}><input value={deviceName()} maxlength="48" onInput={e=>setDeviceName(e.currentTarget.value)} /><button type="button" disabled={busy()!==""||deviceName().trim().length<2} onClick={()=>void addDevice()} {...stylex.props(styles.primary)}>Enroll this browser</button></div><div {...stylex.props(styles.deviceList)}><For each={account()!.devices}>{(device,index)=><article {...stylex.props(styles.device)}><div><strong>{device.name}</strong><div {...stylex.props(styles.muted)}>{device.platform} · {device.attestationProvider||"no provider"} · {device.attestationStatus} · {device.status}</div><div {...stylex.props(styles.deviceMeta)}>Device weight: {index()===0?"100%":index()===1?"25%":index()===2?"10%":"2%"} · hardware-backed: {device.hardwareBacked?"yes":"no"} · testnet eligible: {device.productionEligible?"yes":"no"}</div></div><Show when={device.status==="active"}><button type="button" disabled={busy()!==""} onClick={()=>void run("revoke",()=>authApi.revokeDevice(device.id),"Device revoked.")} {...stylex.props(styles.danger)}>Revoke</button></Show></article>}</For></div></section>
    </Show>
  </section></Shell>;
}

const styles=stylex.create({wrap:{maxWidth:"1050px",margin:"0 auto",padding:"64px 24px"},eyebrow:{color:"#d9f13b",fontSize:"11px",fontWeight:900,letterSpacing:"0.16em"},title:{fontSize:"clamp(48px,8vw,86px)",lineHeight:.94,letterSpacing:"-0.055em",margin:"10px 0"},lede:{maxWidth:"820px",color:"#aeb4a4",fontSize:"18px",lineHeight:1.6},notice:{margin:"22px 0",padding:"12px 14px",border:"1px solid #3b4433",borderRadius:"10px",backgroundColor:"#171a14",color:"#aeb4a4"},grid:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:"14px"},card:{padding:"26px",border:"1px solid #343b2e",borderRadius:"18px",backgroundColor:"#1a1e17"},devices:{marginTop:"14px"},muted:{color:"#8d9584",lineHeight:1.55,fontSize:"13px"},deviceMeta:{color:"#b0b89f",fontSize:"12px",marginTop:"5px"},field:{display:"grid",gap:"7px",marginTop:"18px",color:"#aeb4a4",fontSize:"12px",fontWeight:800},actions:{display:"flex",gap:"10px",flexWrap:"wrap",alignItems:"center",marginTop:"16px"},primary:{border:0,borderRadius:"10px",backgroundColor:"#d9f13b",color:"#11130f",padding:"12px 15px",fontWeight:900,cursor:"pointer",":disabled":{opacity:.4,cursor:"not-allowed"}},secondary:{border:"1px solid #59634b",borderRadius:"10px",backgroundColor:"transparent",color:"#e4e7da",padding:"11px 14px",fontWeight:800,cursor:"pointer"},danger:{border:"1px solid #805c55",borderRadius:"10px",backgroundColor:"transparent",color:"#e0a39a",padding:"10px 13px",fontWeight:800,cursor:"pointer"},details:{display:"grid",gap:"8px"},binding:{display:"grid",gap:"4px",marginTop:"16px",padding:"12px",backgroundColor:"#23291f",borderRadius:"10px"},deviceList:{display:"grid",gap:"9px",marginTop:"18px"},device:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:"12px",padding:"13px",border:"1px solid #30372c",borderRadius:"11px",backgroundColor:"#151813"}});
