import { createRouter } from "@solidjs/router";
import AccountRoute from "./routes/AccountRoute";
import ArenaRoute from "./routes/ArenaRoute";
import CampaignRoute from "./routes/CampaignRoute";
import GameRoute from "./routes/GameRoute";
import HomeRoute from "./routes/HomeRoute";
import NotFoundRoute from "./routes/NotFoundRoute";
import ProfileRoute from "./routes/ProfileRoute";
import ProofOfPlayRoute from "./routes/ProofOfPlayRoute";
import SquadRoute from "./routes/SquadRoute";
export const AppRouter=createRouter({routes:[{path:"/",component:HomeRoute},{path:"/game",component:GameRoute},{path:"/campaign",component:CampaignRoute},{path:"/profile",component:ProfileRoute},{path:"/account",component:AccountRoute},{path:"/arena",component:ArenaRoute},{path:"/squad",component:SquadRoute},{path:"/proof-of-play",component:ProofOfPlayRoute},{path:"*all",component:NotFoundRoute}]});
